'use strict';
// Explicit optional Chromium run: requires the supplied real fixture and browser runtime.
const { test } = require('node:test'), assert = require('node:assert/strict'), fs = require('node:fs/promises'), path = require('node:path');
const { chromium } = require(process.env.HEAPLENS_PLAYWRIGHT_MODULE || 'playwright');
const { BrowserHost } = require('./server.cjs');
const dump = process.env.HEAPLENS_TEST_DUMP, second = process.env.HEAPLENS_TEST_SECOND_DUMP;
assert.ok(dump && second, 'Supply two real fixture paths explicitly; no silently skipped browser tests.');
for (const width of [1280, 640])
    test('shared eleven-tab browser, exports, malicious labels, consent heartbeat and real-server Retry (' + width + 'px)', async (t) => {
        const files = await Promise.all([dump, second].map(async (file) => { const stat = await fs.stat(file); return { path: file, label: path.basename(file), size: stat.size, mtime: stat.mtimeMs }; }));
        const host = await new BrowserHost({ server: process.env.HEAPLENS_TEST_SERVER || path.resolve(__dirname, '../hprof-analyzer/target/release/hprof-server'), files, roots: [], telemetry: 'off' }).listen();
        t.after(() => host.shutdown());
        const browser = await chromium.launch({ headless: true });
        t.after(() => browser.close());
        const page = await browser.newPage({ viewport: { width, height: 850 }, acceptDownloads: true });
        page.setDefaultTimeout(7000);
        const errors = [];
        page.on('pageerror', error => errors.push(error.message));
        await page.route('**/*', route => route.request().url().startsWith(host.origin + '/') ? route.continue() : route.abort());
        const [a, b] = [...host.sessions.values()];
        await page.goto(host.url(a.id));
        await page.waitForFunction(() => document.querySelector('#browser-status').textContent.startsWith('READY'));
        assert.equal(new URL(page.url()).hash, '');
        assert.ok(!(await page.content()).includes(host.token));
        await page.locator('#browser-telemetry').click();
        await page.locator('#browser-dialog button').filter({ hasText: 'Review local diagnostics' }).click();
        await page.waitForFunction(() => document.querySelector('#browser-dialog h2')?.textContent === 'Local filtered diagnostics');
        const diagnostics = JSON.parse(await page.locator('#browser-dialog pre').textContent());
        assert.equal(diagnostics.level, 'off');
        assert.equal(diagnostics.submitted, 0);
        assert.ok(diagnostics.events.some(e => e.name === 'analysis/completed'));
        assert.ok(!JSON.stringify(diagnostics).includes(dump));
        await page.locator('#browser-dialog button').filter({ hasText: 'Close' }).click();
        await page.locator('#browser-telemetry').click();
        await page.locator('#browser-dialog button').filter({ hasText: 'Disable telemetry' }).click();
        await page.waitForFunction(() => document.querySelector('#local-action-status').textContent.includes('Telemetry is off'));
        assert.equal(host.telemetry.level, 'off');
        assert.equal(await page.locator('.tab-btn').count(), 11);
        for (const tab of ['overview', 'histogram', 'domtree', 'leaks', 'waste', 'source', 'query', 'compare', 'timeline', 'monitor', 'chat'])
            await page.locator('#tabBtn-' + tab).click();
        await page.locator('#tabBtn-query').click();
        await page.locator('#query-input').fill('SELECT object_id, class_name, shallow_size, retained_size FROM instances WHERE object_id = 14176760392 OR object_id = 14176760768 OR object_id = 14176762104 OR object_id = 14176766104 OR object_id = 14176776512 ORDER BY object_id');
        await page.locator('#query-run-btn').click();
        await page.waitForFunction(() => document.querySelector('#query-results').textContent.includes('ShallowSizeCounterexample'));
        assert.match(await page.locator('#query-results').textContent(), /152 B/);
        assert.match(await page.locator('#query-results').textContent(), /40 B/);
        await page.locator('#tabBtn-histogram').click();
        await page.locator('#histogram-search').fill('java.lang.String');
        assert.ok(await page.locator('.hist-class-link').count());
        const download = page.waitForEvent('download');
        await page.locator('#export-csv-btn').click();
        const csv = await download;
        assert.equal(csv.suggestedFilename(), 'HeapLens-histogram.csv');
        assert.match(await fs.readFile(await csv.path(), 'utf8'), /java.lang.String/);
        await page.locator('.hist-class-link').first().click();
        await page.locator('.instance-action').first().waitFor({ state: 'visible' });
        assert.ok(await page.locator('.instance-action').count());
        await page.locator('#tabBtn-domtree').click();
        await page.locator('#tab-domtree .tree-inspect:visible').first().click();
        await page.waitForFunction(() => !document.querySelector('#inspector-panel').textContent.includes('Loading'));
        assert.ok(await page.locator('#inspector-panel').textContent());
        await page.locator('.inspector-close').click();
        await page.locator('#domtree-view-flame').click();
        await page.waitForFunction(() => document.querySelector('#sunburst-chart svg'));
        await page.locator('#domtree-view-tree').click();
        await page.locator('#tabBtn-chat').click();
        await page.locator('#ai-configure').click();
        await page.locator('#browser-dialog').waitFor({ state: 'visible' });
        assert.equal(await page.locator('#browser-dialog select option').count(), 10);
        await page.locator('#browser-dialog button').filter({ hasText: 'Cancel' }).click();
        await page.waitForFunction(() => !document.querySelector('#ai-configure').disabled);
        // A modal must not block authenticated polling or trigger the idle timeout.
        a.setConfiguration({ configuration: { provider: 'ollama', model: 'test', baseUrl: 'http://127.0.0.1:1', key: '' } });
        await page.locator('#chat-input').fill('What retains memory?');
        await page.locator('#chat-send').click();
        await page.locator('#browser-dialog').waitFor({ state: 'visible' });
        const seen = host.lastSeen;
        await new Promise(resolve => setTimeout(resolve, 1300));
        assert.ok(host.lastSeen > seen);
        await page.locator('#browser-dialog button').filter({ hasText: 'Cancel' }).click();
        await page.waitForFunction(() => !document.querySelector('#chat-send').disabled);
        const history = page.waitForEvent('download');
        await page.locator('#browser-history').click();
        assert.equal((await history).suggestedFilename(), 'HeapLens-chat.json');
        const other = await browser.newPage();
        other.setDefaultTimeout(7000);
        await other.goto(host.url(b.id));
        await other.waitForFunction(() => document.querySelector('#browser-status').textContent.startsWith('READY'));
        await other.locator('#tabBtn-compare').click();
        await other.locator('#compare-select').selectOption(a.id);
        await other.locator('#compare-btn').click();
        await other.waitForFunction(() => document.querySelector('#compare-results').textContent.includes('Summary Delta'));
        await other.locator('#tabBtn-timeline').click();
        for (const input of await other.locator('#timeline-file-list input[type=checkbox]').all())
            await input.check();
        await other.locator('#timeline-build-btn').click();
        await other.waitForFunction(() => document.querySelector('#timeline-charts').textContent.length > 0);
        const evil = 'evil" autofocus onfocus="window.heaplensInjected=1';
        a.raw.class_histogram = [{ class_name: evil, instance_count: 1, shallow_size: 24, retained_size: 32 }];
        a.emit('analysisProgress', { stage: 'loading', phase: 1, totalPhases: 4 });
        a.ready();
        await page.locator('#tabBtn-histogram').click();
        await page.locator('#histogram-search').fill('evil');
        await page.waitForFunction(() => document.querySelector('.hist-class-link')?.textContent.startsWith('evil'));
        assert.equal(await page.locator('.hist-class-link').getAttribute('data-class'), evil);
        assert.equal(await page.locator('[onfocus]').count(), 0);
        assert.equal(await page.evaluate(() => window.heaplensInjected), undefined);
        const old = a.rpc.child.pid;
        process.kill(old, 'SIGKILL');
        await page.waitForFunction(() => document.querySelector('#browser-status').textContent.includes('UNAVAILABLE'));
        await page.locator('#browser-retry').click();
        await page.waitForFunction(() => document.querySelector('#browser-status').textContent.startsWith('READY'));
        assert.notEqual(a.rpc.child.pid, old);
        assert.equal(b.state, 'ready');
        await page.locator('#tabBtn-query').click();
        await page.locator('#query-input').fill('SELECT object_id FROM instances LIMIT 1');
        await page.locator('#query-run-btn').click();
        await page.waitForFunction(() => document.querySelector('#query-results tbody tr'));
        assert.ok(!(await page.locator('#query-status').textContent()).includes('unavailable'));
        if (process.env.HEAPLENS_BROWSER_EVIDENCE) {
            await page.locator('#tabBtn-overview').click();
            await page.screenshot({ path: path.join(process.env.HEAPLENS_BROWSER_EVIDENCE, 'standalone-' + width + '.png') });
        }
    await page.locator('#browser-stop').click();
    await page.locator('#browser-dialog button').filter({ hasText: 'Confirm' }).click();
    await page.waitForFunction(() => document.querySelector('#browser-status').textContent === 'CLI stopped. Close this page.');
    assert.equal(host.stopped, true);
    assert.equal(a.state, 'closed');
    assert.equal(b.state, 'closed');
    assert.deepEqual(errors, []);
    });
